name: Latest main build
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - run: |
        dotnet publish -o PowerDimmer
        7z a -tzip "PowerDimmer.zip" "./PowerDimmer/*"
        rm -r "PowerDimmer"
    - uses: softprops/action-gh-release@v1
      with:
        prerelease: true
        tag_name: ${{ github.ref_name }}
        files: "PowerDimmer.zip"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
